#!/usr/bin/env python3
"""Regenerate lapse-offsets.json (and the JS tables) from retail firmware.

This is the provenance of every number in lapse-offsets.json and of the GADGETS
/ EXTRA_GADGETS tables in netctrl-ps5.js. Nothing in those tables was typed by
hand; if a firmware needs adding, add it to FIRMWARES and re-run.

    python extract-gadgets.py --db <system_system_ex_database> --check
    python extract-gadgets.py --db <system_system_ex_database> --write

Requires: capstone.

Selection rule
--------------
A gadget's RVA is the FIRST occurrence of its byte pattern inside the module's
executable PT_LOAD segment. That rule is not an assumption — `--check` re-derives
the six firmwares that predate this script (09.00 09.20 09.40 09.60 10.00 10.01)
and requires them to come out byte-identical to what is already published. Every
emitted RVA is additionally disassembled and string-compared against the gadget
it claims to be, so a pattern sitting in a constant pool cannot slip through.

Bases
-----
  webkit        -> libSceNKWebKit.sprx   (runtime slopkit.webkitBase)
  libkernel_web -> libkernel_web.sprx    (runtime slopkit.kernelBase)
RVAs are module virtual addresses, i.e. exactly what gets added to those bases.
"""

import argparse
import collections
import glob
import json
import os
import struct
import sys

try:
    from capstone import Cs, CS_ARCH_X86, CS_MODE_64
except ImportError:
    sys.exit("capstone is required:  pip install capstone")

PT_LOAD = 1
PF_X = 1

FIRMWARES = [
    "09.00", "09.20", "09.40", "09.60",
    "10.00", "10.01", "10.20", "10.40", "10.60",
    "11.00", "11.20", "11.40", "11.60",
    # 12.02+ are the p2jb window: the netcontrol bug is fixed there, but the
    # WebKit stage and every ROP gadget still resolve, so they get full tables.
    "12.00", "12.02", "12.20", "12.40", "12.60", "12.70",
]

# Located by glob rather than a fixed path: the extraction layout is not uniform
# across the database. Most firmware directories nest under "PS5UPDATE.PUP_out",
# but 12.02 / 12.40 / 12.60 / 12.70 use "<build>.PUP_out" (e.g. "1202.PUP_out"),
# and a hardcoded path silently reports every gadget as missing on exactly those
# — which reads as "the module changed" rather than "you looked in the wrong
# place".
WEBKIT_NAME = "libSceNKWebKit.sprx"
LIBK_NAME = "libkernel_web.sprx"


def _find(fwdir, name):
    hits = glob.glob(os.path.join(fwdir, "**", name), recursive=True)
    if not hits:
        sys.exit("%s: cannot find %s under %s" % (os.path.basename(fwdir), name, fwdir))
    return hits[0]

# name -> (pattern, exact capstone rendering the bytes MUST decode to)
GADGETS = collections.OrderedDict([
    ("pop_rax",           (b"\x58\xc3",                 "pop rax; ret")),
    ("pop_rdi",           (b"\x5f\xc3",                 "pop rdi; ret")),
    ("pop_rsi",           (b"\x5e\xc3",                 "pop rsi; ret")),
    ("pop_rdx",           (b"\x5a\xc3",                 "pop rdx; ret")),
    ("pop_rcx",           (b"\x59\xc3",                 "pop rcx; ret")),
    ("pop_rbx",           (b"\x5b\xc3",                 "pop rbx; ret")),
    ("pop_rbp",           (b"\x5d\xc3",                 "pop rbp; ret")),
    ("pop_r8",            (b"\x41\x58\xc3",             "pop r8; ret")),
    ("mov_qword_rdi_rax", (b"\x48\x89\x07\xc3",         "mov qword ptr [rdi], rax; ret")),
    ("mov_rsp_rbp",       (b"\x48\x89\xec\x5d\xc3",     "mov rsp, rbp; pop rbp; ret")),
    ("pivot_rdi_rsp",     (b"\x48\x89\xfc\xc3",         "mov rsp, rdi; ret")),
    ("ret",               (b"\xc3",                     "ret")),
])
SYSCALL_WRAPPER = (b"\x49\x89\xca\x0f\x05\xc3", "mov r10, rcx; syscall; ret")

# Human-readable `desc` written into the JSON.
DESC = {k: v[1].replace("qword ptr ", "qword ") for k, v in GADGETS.items()}
DESC["syscall_wrapper"] = SYSCALL_WRAPPER[1]

# setjmp/longjmp are found by function prologue, not by symbol: the values these
# entries originally carried (0x58f80 / 0x58fd0) pointed at data. Both prologues
# are byte-identical across the whole 09.00-12.00 window.
SIG_SETJMP = bytes.fromhex("4889f9488b1424488911488959084889")
SIG_LONGJMP = bytes.fromhex("4889fa89f0488b0a488b5a08488b6210")

# Struct offsets consumed by lapse-runtime; invariant across this window.
KERNEL_OFFSET = collections.OrderedDict([
    ("PROC_PID", "0xbc"), ("PROC_FD", "0x48"), ("SIZEOF_OFILES", "0x30"),
    ("SO_PCB", "0x18"), ("INPCB_PKTOPTS", "0x118"), ("FILEDESC_OFILES", "0x0"),
])

COMMENT = (
    "Per-fw gadget + kernel-offset table for lapse. Two ROP bases: `webkit` = "
    "libSceNKWebKit.sprx (slopkit.webkitBase). `libkernel_web` = "
    "libkernel_web.sprx (slopkit.kernelBase). All gadgets pad=0 (clean pop; ret) "
    "so lapse.js's chain-building convention works without modification. "
    "mov_rax_0x200000000 does not exist in either module — lapse.js patched "
    "to use pop_rax + 0x200000000n. "
    "GENERATED by offsets/extract-gadgets.py — do not hand-edit. Covers "
    "09.00 → 12.00, the full netcontrol-UAF window. Every RVA is the first "
    "occurrence of the gadget's byte pattern in the module's executable PT_LOAD, "
    "and each one was disassembled and string-matched against its `desc` before "
    "being written. setjmp/longjmp are recovered by prologue signature (the "
    "original 0x58f80/0x58fd0 pointed at data). `ret` was 0xc2 on every "
    "firmware, which actually decodes to `pop r14; pop r15; pop rbp; ret`; it is "
    "now a true one-byte ret — nothing reads ROP.ret today, so that is a "
    "latent-bug fix rather than a behaviour change."
)


def read_segments(path):
    d = open(path, "rb").read()
    e_phoff, = struct.unpack_from("<Q", d, 0x20)
    e_phentsize, = struct.unpack_from("<H", d, 0x36)
    e_phnum, = struct.unpack_from("<H", d, 0x38)
    segs = []
    for i in range(e_phnum):
        o = e_phoff + i * e_phentsize
        p_type, p_flags = struct.unpack_from("<II", d, o)
        p_off, p_va, _pa, p_fsz, _msz, _al = struct.unpack_from("<6Q", d, o + 8)
        if p_type == PT_LOAD and (p_flags & PF_X):
            segs.append((p_off, p_va, p_fsz))
    return d, segs


def first_match(d, segs, pattern):
    for off, va, fsz in segs:
        i = d.find(pattern, off, off + fsz)
        if i >= 0:
            return va + (i - off)
    return None


def disasm_gadget(d, segs, rva):
    """Render the instructions at rva up to and including the first ret."""
    for off, va, fsz in segs:
        if va <= rva < va + fsz:
            blob = d[off + (rva - va):off + (rva - va) + 16]
            out = []
            for ins in Cs(CS_ARCH_X86, CS_MODE_64).disasm(blob, rva):
                out.append(("%s %s" % (ins.mnemonic, ins.op_str)).strip())
                if ins.mnemonic == "ret":
                    break
            return "; ".join(out)
    return None


def extract(db, fw):
    base = os.path.join(db, str(int(fw.split(".")[0])), "Firmware %s.00" % fw)
    wk_path, lk_path = _find(base, WEBKIT_NAME), _find(base, LIBK_NAME)

    wd, wsegs = read_segments(wk_path)
    ld, lsegs = read_segments(lk_path)

    entry = collections.OrderedDict()

    webkit = collections.OrderedDict()
    for name, (pat, want) in GADGETS.items():
        rva = first_match(wd, wsegs, pat)
        if rva is None:
            sys.exit("%s: no %s in libSceNKWebKit" % (fw, name))
        got = disasm_gadget(wd, wsegs, rva)
        if got != want:
            sys.exit("%s: %s at %#x decodes to %r, expected %r"
                     % (fw, name, rva, got, want))
        webkit[name] = collections.OrderedDict(
            [("rva", hex(rva)), ("pad", 0), ("desc", DESC[name])])
    entry["webkit"] = webkit

    libk = collections.OrderedDict()
    pat, want = SYSCALL_WRAPPER
    rva = first_match(ld, lsegs, pat)
    if rva is None:
        sys.exit("%s: no syscall_wrapper in libkernel_web" % fw)
    got = disasm_gadget(ld, lsegs, rva)
    if got != want:
        sys.exit("%s: syscall_wrapper at %#x decodes to %r" % (fw, rva, got))
    libk["syscall_wrapper"] = collections.OrderedDict(
        [("rva", hex(rva)), ("pad", 0), ("desc", DESC["syscall_wrapper"])])

    for name, sig in (("setjmp", SIG_SETJMP), ("longjmp", SIG_LONGJMP)):
        rva = first_match(ld, lsegs, sig)
        if rva is None:
            sys.exit("%s: %s prologue signature not found" % (fw, name))
        libk[name] = collections.OrderedDict(
            [("rva", hex(rva)), ("pad", 0),
             ("desc", "%s entry, recovered by prologue signature" % name)])
    entry["libkernel_web"] = libk

    entry["kernel_offset"] = KERNEL_OFFSET
    return entry


def extract_ropw(db, fw):
    """rop-worker.js's per-firmware libkernel_web constants.

    These were 10.00-only bare constants until a 12.00 console failed in fire()
    with "slot holds libkernel+0x6d1d0, expected +0x190db".
    """
    base = os.path.join(db, str(int(fw.split(".")[0])), "Firmware %s.00" % fw)
    lk_path, wk_path = _find(base, LIBK_NAME), _find(base, WEBKIT_NAME)
    ld, lsegs = read_segments(lk_path)

    # pop rsp; ret. Absent from libkernel_web on 11.x/12.00 (zero hits), so fall
    # back to libSceNKWebKit and record which module the RVA belongs to.
    mod, rva = "lk", first_match(ld, lsegs, b"\x5c\xc3")
    if rva is None:
        wd, wsegs = read_segments(wk_path)
        mod, rva = "wk", first_match(wd, wsegs, b"\x5c\xc3")
        got = disasm_gadget(wd, wsegs, rva) if rva is not None else None
    else:
        got = disasm_gadget(ld, lsegs, rva)
    if rva is None or got != "pop rsp; ret":
        sys.exit("%s: pop_rsp not found in either module (got %r)" % (fw, got))

    sw = first_match(ld, lsegs, SYSCALL_WRAPPER[0])
    sj = first_match(ld, lsegs, SIG_SETJMP)
    lj = first_match(ld, lsegs, SIG_LONGJMP)

    # The two `call pthread_cond_wait` return addresses. Same call shape in all
    # fourteen builds: mov rdi,r14; mov rsi,rbx; mov ecx,1; xor edx,edx;
    # xor r8d,r8d; call rel32; jmp rel8 — the return address is the `jmp`.
    import re as _re
    off, va, fsz = lsegs[0]
    text = ld[off:off + fsz]
    pat = _re.compile(rb"\x4c\x89\xf7\x48\x89\xde\xb9\x01\x00\x00\x00"
                      rb"\x31\xd2\x45\x31\xc0\xe8(....)\xeb", _re.S)
    cw = [va + m.start() + 21 for m in pat.finditer(text)]
    if len(cw) < 2:
        sys.exit("%s: expected 2 cond_wait call sites, found %d" % (fw, len(cw)))

    return collections.OrderedDict([
        ("pop_rsp_mod", mod), ("pop_rsp", rva), ("text", fsz),
        ("syscall_wrapper", sw), ("setjmp", sj), ("longjmp", lj),
        ("cond_wait_ret", cw[0]), ("cond_wait_ret2", cw[1]),
    ])


def emit_ropw(db):
    print("const LKW_TABLE = {")
    for fw in FIRMWARES:
        r = extract_ropw(db, fw)
        print('    "%s": { pop_rsp: { mod: "%s", rva: 0x%05Xn }, text: 0x%Xn, '
              'syscall_wrapper: 0x%Xn, setjmp: 0x%Xn, longjmp: 0x%Xn, '
              'cond_wait_ret: 0x%Xn, cond_wait_ret2: 0x%Xn },'
              % (fw, r["pop_rsp_mod"], r["pop_rsp"], r["text"],
                 r["syscall_wrapper"], r["setjmp"], r["longjmp"],
                 r["cond_wait_ret"], r["cond_wait_ret2"]))
    print("};")


def emit_js(table):
    """Print the netctrl-ps5.js GADGETS / EXTRA_GADGETS literals."""
    print("const GADGETS = {")
    for fw, e in table.items():
        w, s = e["webkit"], e["libkernel_web"]["syscall_wrapper"]["rva"]
        print('    "%s": { mov_rsp_rbp: %sn, pivot_rdi_rsp: %sn, pop_r8: %sn,\n'
              '               pop_rax: %sn, pop_rcx: %sn, pop_rdi: %sn,\n'
              '               pop_rdx: %sn, pop_rsi: %sn, syscall_wrapper: %sn },'
              % (fw, w["mov_rsp_rbp"]["rva"], w["pivot_rdi_rsp"]["rva"],
                 w["pop_r8"]["rva"], w["pop_rax"]["rva"], w["pop_rcx"]["rva"],
                 w["pop_rdi"]["rva"], w["pop_rdx"]["rva"], w["pop_rsi"]["rva"], s))
    print("};\n")
    print("const EXTRA_GADGETS = {")
    for fw, e in table.items():
        print('    "%s": { mov_qword_rdi_rax: %sn },'
              % (fw, e["webkit"]["mov_qword_rdi_rax"]["rva"].upper()
                     .replace("0X", "0x")))
    print("};")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", required=True,
                    help="path to system_system_ex_database (the dir holding 9/ 10/ 11/ 12/)")
    ap.add_argument("--write", action="store_true",
                    help="overwrite lapse-offsets.json next to this script")
    ap.add_argument("--check", action="store_true",
                    help="compare against the existing lapse-offsets.json and exit nonzero on drift")
    ap.add_argument("--js", action="store_true",
                    help="print the netctrl-ps5.js table literals")
    ap.add_argument("--ropw", action="store_true",
                    help="print the rop-worker.js LKW_TABLE literal")
    args = ap.parse_args()

    if args.ropw:
        emit_ropw(args.db)
        if not (args.write or args.check or args.js):
            return 0

    table = collections.OrderedDict()
    for fw in FIRMWARES:
        sys.stderr.write("extracting %s ...\n" % fw)
        table[fw] = extract(args.db, fw)

    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "lapse-offsets.json")

    if args.check:
        old = json.load(open(out_path))
        drift = 0
        for fw, e in table.items():
            if fw not in old:
                print("NEW  %s (not in published table)" % fw)
                continue
            for mod in ("webkit", "libkernel_web"):
                for k, v in e[mod].items():
                    o = old[fw].get(mod, {}).get(k)
                    if o is None:
                        print("MISSING %s %s.%s in published table" % (fw, mod, k))
                        drift += 1
                    elif int(o["rva"], 16) != int(v["rva"], 16):
                        print("DRIFT   %s %s.%s published=%s derived=%s"
                              % (fw, mod, k, o["rva"], v["rva"]))
                        drift += 1
        print("drift: %d" % drift)
        return 1 if drift else 0

    if args.js:
        emit_js(table)

    if args.write:
        doc = collections.OrderedDict([("_comment", COMMENT)])
        doc.update(table)
        with open(out_path, "w", newline="\n") as f:
            json.dump(doc, f, indent=1)
            f.write("\n")
        sys.stderr.write("wrote %s (%d firmwares)\n" % (out_path, len(table)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
